server:
  port: 8866

mqtt:
  host: tcp://192.168.3.3:1883 # MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://127.0.0.1:61613, tcp://192.168.2.133:61613
  clientId: ${random.int}  # MQTT-连接服务器默认客户端 ID
  userName: rabbitmq   # MQTT-用户名
  passWord: 123456 # MQTT-密码
  default-topic: amq.topic # MQTT-默认的消息推送主题，实际可在调用接口时指定，主题遵循通配符，通过通配符可以匹配多个主题
  timeOut: 1000 # 连接超时
  keepAlive: 30   # 设置会话心跳时间
  clearSession: true  # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)

